name: flutter_counter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  bloc_test: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
  #integration_test: ^1.0.2+3

flutter:
  uses-material-design: true
